export const WATERMARK_TEXT = 'generated by DhandaX Tools';

export const printHtmlDocument = (title: string, bodyHtml: string, width = 900, height = 900) => {
  const popup = window.open('', '_blank', `width=${width},height=${height}`);
  if (!popup) return false;

  popup.document.write(`
    <html>
      <head>
        <title>${title}</title>
      </head>
      <body style="font-family: Manrope, Arial, sans-serif; padding: 28px; color:#0f172a; position:relative;">
        <div style="position:fixed; top:16px; right:24px; font-size:11px; color:#64748b; letter-spacing:0.03em;">
          ${WATERMARK_TEXT}
        </div>
        ${bodyHtml}
      </body>
    </html>
  `);
  popup.document.close();
  popup.focus();
  popup.print();
  return true;
};
